
name: CD-prod

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci       
      - run: npm run build
        env:
          NODE_ENV: production
          REACT_APP_HERE_MAPS_API_KEY: ${{ secrets.REACT_APP_HERE_MAPS_API_KEY }}
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: aws s3 sync ./build s3://harta.sprijindeurgenta.ro --delete 
          
      - uses: awact/cloudfront-action@master
        env:
          AWS_REGION: 'eu-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
